# Generated by Django 5.0.6 on 2024-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guiding_light', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('chdoc', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
